### ISSUE TITLE
TOO slow

### ISSUE THREAD

**Issue by gauravkrp** [ironmaniiith/mi.com.hack#3] opened 2016-07-17 22:33 UTC
too slow after level 40. unable to pair all in 30 seconds. kindly speed it up!

**Comment by ironmaniiith** [comment] 2016-07-17 22:40
Duplicate of #1
@gauravkrp, I know this is the issue, but I intentionally left it for the users so that they at least apply "some" effort to reach at the top :wink: 
Also I had received many good responses, because when tried on their own, they were very happy..

Anyways I will modify the script after some time, thanks.

**Comment by ironmaniiith** [comment] 2016-07-17 22:40
And ya, if you liked the work, please like my videos and subscribe to my channel for more such videos and hacks in future :smile:

**Comment by gauravkrp** [comment] 2016-07-17 23:03
I tried and tried! and I succeeded! but 450 rank :-( anyway, thanks! keep it up!﻿

**Comment by ironmaniiith** [comment] 2016-07-17 23:14
Haha, worth is of hardwork, Nice job :smile: 
Make sure to like and subscribe to my channel for more such hacks and videos in future :smile:

**Closed as completed** 2016-07-17 23:14 UTC

**Comment by gauravkrp** [comment] 2016-07-20 06:59
Buddy! used your pair2win script. it was great! Do you have script for today's flash sale?
